/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.geoteam.geostory;

public final class Manifest {
    public static final class permission {
        /**  needed permissions for google maps 
         */
        public static final String MAPS_RECEIVE="com.geoteam.GeoStory.permission.MAPS_RECEIVE";
    }
}
